# Generated by Django 5.1.7 on 2025-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_stratum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='stratum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
