# Generated by Django 5.1.7 on 2025-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_property_stratum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='age',
            field=models.CharField(blank=True, choices=[('1 a 8 años', '1 a 8 años'), ('9 a 15 años', '9 a 15 años'), ('16 a 30 años', '16 a 30 años'), ('Más de 30 años', 'Más de 30 años')], max_length=50, null=True),
        ),
    ]
